name = "VPIN"
uuid = "98b75bef-cec7-42fd-9fd8-1608d125fef6"
authors = ["fanjinyun"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
